accounts/urls.py
from django.urls import path
from .views import register, login_view, logout_view


app_name = 'accounts'

urlpatterns = [
    path('register/', register, name='register'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
]

lucantel/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('accounts/', include('accounts.urls')),
]

website/urls.py
# urls for website

from django.urls import path, include
from . import views

from django.conf import settings
from django.conf.urls.static import static

app_name = 'website'

urlpatterns = [
    path('', views.index, name='index'),
    path('accounts/', include('accounts.urls')),
    path('app/', views.app, name='app'),
    path('upload/', views.upload_files, name='upload_files'),
    path('list_images/', views.list_images, name='list_images'),
    path('create_dataset/', views.create_dataset, name='create_dataset'),
    path('delete_dataset/', views.delete_dataset, name='delete_dataset'),
    path('list_datasets/', views.list_datasets, name='list_datasets'),   
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

website/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from typing import Any
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=30, required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs['placeholder'] = 'First Name'
        self.fields['last_name'].widget.attrs['placeholder'] = 'Last Name'
        self.fields['email'].widget.attrs['placeholder'] = 'Email'
        self.fields['username'].widget.attrs['placeholder'] = 'Username'
        self.fields['password1'].widget.attrs['placeholder'] = 'Password'
        self.fields['password2'].widget.attrs['placeholder'] = 'Confirm Password'
        # for field in self.fields:
        #     self.fields[field].widget.attrs['class'] = 'form-control {{ widget.attrs.class }}'

accounts/views.py
from django.shortcuts import render

# Create your views here.

from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import AuthenticationForm
from .forms import RegisterForm

def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.first_name = form.cleaned_data.get('first_name')
            user.last_name = form.cleaned_data.get('last_name')
            user.save()
            login(request, user)
            return redirect('website:index')  # Redirect to the index page after successful registration
    else:
        form = RegisterForm()
    return render(request, 'accounts/register.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('website:app')  # Redirect to a success page.
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})

def logout_view(request):
    logout(request)
    return redirect('website:index')  # Redirect to the index page after logout

website/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse

import os

UPLOAD_FOLDER = 'uploads'

# Create your views here.

def index(request):
    return render(request, 'index.html')

@login_required
def app(request):
    list_datasets(request)
    return render(request, 'app.html')

def create_user_media_folder(request):
    # get user
    user = request.user  
    # create user media folder
    media_folder = os.path.join(UPLOAD_FOLDER, user.username)  
    os.makedirs(media_folder, exist_ok=True)
    return media_folder

@csrf_exempt
def upload_files(request):
    user_media_folder = create_user_media_folder(request)
    if request.method == 'POST':        
        dataset = request.POST.get('dataset')
        dataset_folder = os.path.join(user_media_folder, dataset)
        files = request.FILES.getlist('images')
        print(files)
        if files is None or len(files) == 0:
            return JsonResponse({'error': 'No files found in the request'}, status=400)
        # Delete files in the folder
        for file in os.listdir(dataset_folder):
            os.remove(os.path.join(dataset_folder, file))
        # Save files to the folder
        for file in files:
            with open(os.path.join(dataset_folder, file.name), 'wb+') as destination:
                for chunk in file.chunks():
                    destination.write(chunk)
        files_count = len(os.listdir(dataset_folder))
        return JsonResponse({'message': 'Files successfully uploaded', "files_count":files_count}, status=200)
    return JsonResponse({'error': 'Invalid request'}, status=400)

def list_images(request):
    user_media_folder = create_user_media_folder(request)
    if request.method == 'GET' and 'dataset' in request.GET:  
        dataset = request.GET.get('dataset')
        if not dataset:
            return JsonResponse({'error': 'Dataset is required'}, status=400)
        print(dataset)
        dataset_folder = os.path.join(user_media_folder, dataset) 
        print(dataset_folder)  
        images = os.listdir(os.path.join(dataset_folder))
        image_urls = [os.path.join(dataset_folder, image) for image in images]
        print(image_urls)
        return JsonResponse({'images': image_urls[:5]}, status=200)
    else:
        return JsonResponse({'error': 'Invalid request'}, status=400)

def create_dataset(request):
    if request.method == 'POST':
        user = request.user
        dataset_name = request.POST.get('dataset_name')
        if not dataset_name:
            return JsonResponse({'error': 'Dataset name is required'}, status=400)
        
        user_media_folder = os.path.join(UPLOAD_FOLDER, user.username)
        dataset_folder = os.path.join(user_media_folder, dataset_name)
        
        if not os.path.exists(dataset_folder):
            os.makedirs(dataset_folder)
            return JsonResponse({'message': 'Dataset created successfully'}, status=201)
        else:
            return JsonResponse({'error': 'Dataset already exists'}, status=400)
    
    return JsonResponse({'error': 'Invalid request'}, status=400)


def delete_dataset(request):
    if request.method == 'GET':
        user = request.user
        dataset_name = request.GET.get('dataset')
        print(dataset_name)
        if not dataset_name:
            return JsonResponse({'error': 'Dataset name is required'}, status=400)
        
        user_media_folder = os.path.join(UPLOAD_FOLDER, user.username)
        dataset_folder = os.path.join(user_media_folder, dataset_name)
        
        if not os.path.exists(dataset_folder):            
            return JsonResponse({'error': 'No dataset selected'}, status=400)
        else:
            # Delete directory and its contents
            print(dataset_folder)
            os.system(f'rm -rf "{dataset_folder}"')
            return JsonResponse({'message': 'Dataset deleted successfully'}, status=200)
    
    return JsonResponse({'error': 'Invalid request'}, status=400)

def list_datasets(request):
    if request.method == 'GET':
        user = request.user
        user_media_folder = os.path.join(UPLOAD_FOLDER, user.username)
        
        if not os.path.exists(user_media_folder):
            return JsonResponse({'datasets': []}, status=200)
        
        datasets = [d for d in os.listdir(user_media_folder) if os.path.isdir(os.path.join(user_media_folder, d))]
        return JsonResponse({'datasets': datasets}, status=200)
    
    return JsonResponse({'error': 'Invalid request'}, status=400)  

templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Login{% endblock %}
{% block content %}
<link rel="stylesheet" href="{% static 'accounts/css/forms.css' %}">    
<div class="form-container">
    <div class="register-container-text">
        <h2 class="text-center register-text">Login</h2>
        <p class="text-center register-text">Please login to your account. If you do not have an account, you can register <a href="{% url 'accounts:register' %}">here</a>.</p>
    </div>
        <form novalidate action="{% url 'accounts:login' %}" method="post">
            {% csrf_token %}
            {{ form }}
            <button type="submit" class="btn btn-primary mt-3 button">Sign in</button>
        </form>
    </div>
{% endblock %}

templates/accounts/register.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Login{% endblock %}
{% block content %}
<link rel="stylesheet" href="{% static 'accounts/css/forms.css' %}">
    <div class="form-container">
    <div class="register-container-text">
        <h2 class="text-center register-text">Register</h2>
        <p class="text-center register-text">Create an account to get started!</p>
    </div>
        <form novalidate action="{% url 'accounts:register' %}" method="post">
            {% csrf_token %}
            {{ form }}
            <button type="submit" class="btn btn-primary mt-3 button">Register</button>
        </form>
    </div>
{% endblock %}

templates/app.html
{% extends 'app_base.html' %}
{% load static %}
{% block title %}App{% endblock %}

{% block content %}
    {% if user.is_authenticated %}

    {% include 'app_index.html' %}

    {% endif %}
{% endblock %}

templates/app_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Lucantel{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="{% static 'accounts/css/forms.css' %}" rel="stylesheet">
    <style>
        body {
            display: flex;
        }
        main {
            width: auto;
            background-color: #f8f9fa;
        }
        .main-content {
            flex-grow: 1;
        }
    </style>

</head>
<body>
    <!-- Sidebar -->
    {% if user.is_authenticated %}
    {% include 'sidebar.html' %}
    {% else %}
    <p><a href="{% url 'accounts:login' %}">Login</a></p>
    {% endif %}
    <!-- End Sidebar -->
    <!-- Content  -->
    <div class="main-content">
    {% block content %}
    {% endblock %}
    </div> 
    <!-- End Content -->

</body>
</html>

templates/app_index.html
{% load static %}
<style>
    .app-content {
        padding: 20px;
    }
</style>

<div class="app-content">
    <h1>Home</h1>
    <div>
        <!-- New form to create a dataset -->
        <form id="createDatasetForm">
            <input type="text" id="datasetName" name="dataset_name" placeholder="Dataset Name">
            <button type="button" class="button-app" onclick="createDataset()">Create Dataset</button>
        </form>
        <!-- Dropdown menu to list datasets -->
        <select id="datasetDropdown">
            <option value="">Select a dataset</option>            
        </select>
        <!-- New form to delete a dataset -->
        <form id="deleteDatasetForm">
            <button type="button" class="button-app" onclick="deleteDataset()">Delete Dataset</button>
        </form>
        <form id="uploadForm" enctype="multipart/form-data">
            <input type="file" id="fileInput" name="images" multiple>
            <button type="button" class="button-app" onclick="uploadImages()">Upload</button>
        </form>        
        <button type="button" class="button-app" onclick="showImages()">Show Images</button>
        <div id="imageGrid" style="display: grid; grid-template-columns: repeat(auto-fill, minmax(100px, 1fr)); gap: 10px;"></div>
        <p id="fileCount"></p>
        
        <script>
            function uploadImages() {
                const form = document.getElementById('uploadForm');
                const formData = new FormData(form);
                
                // Get the selected dataset
                const selectedDataset = document.getElementById('datasetDropdown').value;
                
                // Add the selected dataset to the form data
                formData.append('dataset', selectedDataset);
        
                fetch('/upload/', {
                    method: 'POST',
                    body: formData,
                    headers: {
                        'X-CSRFToken': '{{ csrf_token }}'
                    }
                })
                .then(response => {
                    if (!response.ok) {
                        return response.json().then(data => {
                            throw new Error(data.error || 'Unknown error');
                        });
                    }
                    return response.json();
                })
                .then(data => {
                    console.log('Success:', data);                    
                    document.getElementById('fileCount').innerText = `${data.files_count} files uploaded`;
                })
                .catch(error => {
                    console.error('Error:', error);
                    alert(error.message);
                }); 
            }
            function showImages() {           
                // Get the selected dataset
                const selectedDataset = document.getElementById('datasetDropdown').value;

                fetch(`/list_images/?dataset=${selectedDataset}`)
                .then(response => {
                    if (!response.ok) {
                        return response.json().then(data => {
                            throw new Error(data.error || 'Unknown error');
                        });
                    }
                    return response.json();
                })
                .then(data => {
                    if (data.images.length === 0) {
                        alert('No images found in the dataset');
                        return;
                    }
                    const imageGrid = document.getElementById('imageGrid');
                    imageGrid.innerHTML = '';
                    data.images.forEach(image => {
                        const imgElement = document.createElement('img');
                        imgElement.src = `/${image}`;
                        imgElement.style.width = '100px';
                        imgElement.style.height = '100px';
                        imgElement.style.objectFit = 'cover';
                        imageGrid.appendChild(imgElement);
                    });
                })
                .catch(error => {
                    console.error('Error:', error);
                    alert(error.message);
                }); 
            }        
                
            function createDataset() {
                const form = document.getElementById('createDatasetForm');
                const formData = new FormData(form);
                
                fetch('/create_dataset/', {
                    method: 'POST',
                    body: formData,
                    headers: {
                        'X-CSRFToken': '{{ csrf_token }}'
                    }
                })
                .then(response => {
                    if (!response.ok) {
                        return response.json().then(data => {
                            throw new Error(data.error || 'Unknown error');
                        });
                    }
                    return response.json();
                })
                .then(data => {
                    alert('Dataset created successfully');
                    console.log('Success:', data);
                    loadDatasets();
                })
                .catch(error => {
                    console.error('Error:', error);
                    alert(error.message);
                });                
            }
            function deleteDataset() {
                // Get the selected dataset
                const selectedDataset = document.getElementById('datasetDropdown').value;
                const encodedDataset = encodeURIComponent(selectedDataset);

                fetch(`/delete_dataset/?dataset=${encodedDataset}`)
                .then(response => {
                    if (!response.ok) {
                        return response.json().then(data => {
                            throw new Error(data.error || 'Unknown error');
                        });
                    }
                    return response.json();
                })
                .then(data => {
                    console.log('Success:', data);
                    alert('Dataset deleted successfully');
                    loadDatasets();
                })
                .catch(error => {
                    console.error('Error:', error);
                    alert(error.message);
                });                
            }
            function loadDatasets() {
                fetch('/list_datasets/')
                .then(response => {
                    if (!response.ok) {
                        return response.json().then(data => {
                            throw new Error(data.error || 'Unknown error');
                        });
                    }
                    return response.json();
                })
                .then(data => {
                    const dropdown = document.getElementById('datasetDropdown');
                    dropdown.innerHTML = '<option value="">Select a dataset</option>';
                    data.datasets.forEach(dataset => {
                        const option = document.createElement('option');
                        option.value = dataset;
                        option.text = dataset;
                        dropdown.appendChild(option);
                    });
                })
                .catch(error => {
                    console.error('Error:', error);
                    alert('Error creating dataset: ' + error.message);
                });  
            }
            // Load datasets when the page loads
            document.addEventListener('DOMContentLoaded', loadDatasets);
        </script>
    </div>
</div>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Lucantel{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">    
</head>
<body>
    <!-- Header -->
    {% include 'header.html' %}
    <!-- End Header -->
    <!-- Content  -->
    {% block content %}
    {% endblock %}
    <!-- End Content -->
</body>
</html>

templates/django/forms/label.html
{% if use_tag %}<{{ tag }}{% include 'django/forms/attrs.html' %} class="form-label">{{ label }}</{{ tag }}>{% else %}{{ label }}{% endif %}

templates/django/forms/widgets/input.html
<input class="form-control {{ widget.attrs.class }}" type="{{ widget.type }}" name="{{ widget.name }}" {% if widget.value is not None %} value="{{ widget.value|stringformat:'s' }}" {% endif %}{% include "django/forms/widgets/attrs.html" %}>

templates/form_snippet.html
{% load add_class %}

{% for field in form %}
<div class="mb-3">
    {{ field.label_tag }}
    {% if field.errors %}
        {{ field | add_class:'class:is-invalid' }}
    {% else %}
        {{ field }}
    {% endif %}
    <div class="invalid-feedback">
    {% for error in field.errors %}
        {{ error }}
    {% endfor %}
    </div>
</div>
{% endfor %}

templates/header.html
{% load static %}
<link href="{% static 'website/css/styles.css' %}" rel="stylesheet">
<header class="p-3 bg-secondary-custom text-white">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap">
                    <use xlink:href="#bootstrap" />
                </svg>
            </a>

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="{% url 'website:index' %}" class="nav-link px-2 text-white">Home</a></li>
                <li><a href="#" class="nav-link px-2 text-white">Features</a></li>
                <li><a href="#" class="nav-link px-2 text-white">Pricing</a></li>
                <li><a href="#" class="nav-link px-2 text-white">FAQs</a></li>
                <li><a href="#" class="nav-link px-2 text-white">About</a></li>
                <li><a href="{% url 'website:app' %}" class="nav-link px-2 text-white">App</a></li>
            </ul>

            <div class="d-flex">
                {% if user.is_authenticated %}
                <div class="nav-link px-2 text-white">Welcome, {{ user.username }}!</div>
                <a href="{% url 'accounts:logout' %}" class="btn btn-dark-custom">Logout</a>
                {% else %}
                <div class="nav-link px-2 text-white">You are not logged in.</div>
                <a href="{% url 'accounts:login' %}" class="btn btn-dark-custom">Login</a>
                <a href="{% url 'accounts:register' %}" class="btn btn-dark-custom">Register</a>
                {% endif %}
            </div>
        </div>
    </div>
</header>

templates/index.html
{% extends "base.html" %}

{% block content %}
    <h1>Home</h1>
    <p>Welcome to the home page!</p>
{% endblock %}

templates/sidebar.html
{% load static %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<link href="{% static 'website/css/styles.css' %}" rel="stylesheet">
<link href="{% static 'website/css/sidebars.css' %}" rel="stylesheet">
<style>
  .bd-placeholder-img {
    font-size: 1.125rem;
    text-anchor: middle;
    -webkit-user-select: none;
    -moz-user-select: none;
    user-select: none;
  }

  @media (min-width: 768px) {
    .bd-placeholder-img-lg {
      font-size: 3.5rem;
    }
  }
</style>
<main>
<div class="d-flex flex-column flex-shrink-0 p-3 text-white bg-secondary-custom" style="width: 280px;">
    <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
      <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"/></svg>
      <span class="fs-4">Lucantel</span>
    </a>
    <hr>
    <ul class="nav nav-pills flex-column mb-auto">
      <li class="nav-item">
        <a href="#" class="nav-link active" aria-current="page">
          <svg class="bi me-2" width="16" height="16"><use xlink:href="#home"/></svg>
          Home
        </a>
      </li>
      <li>
        <a href="#" class="nav-link text-white">
          <svg class="bi me-2" width="16" height="16"><use xlink:href="#speedometer2"/></svg>
          Dashboard
        </a>
      </li>
      <li>
        <a href="#" class="nav-link text-white">
          <svg class="bi me-2" width="16" height="16"><use xlink:href="#table"/></svg>
          Orders
        </a>
      </li>
      <li>
        <a href="#" class="nav-link text-white">
          <svg class="bi me-2" width="16" height="16"><use xlink:href="#grid"/></svg>
          Products
        </a>
      </li>
      <li>
        <a href="#" class="nav-link text-white">
          <svg class="bi me-2" width="16" height="16"><use xlink:href="#people-circle"/></svg>
          Customers
        </a>
      </li>
    </ul>
    <hr>
    <div class="dropdown">
      <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
        <img src="https://github.com/mdo.png" alt="" width="32" height="32" class="rounded-circle me-2">
        <strong>{{ user.username }}</strong>
      </a>
      <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
        <li><a class="dropdown-item" href="#">New project...</a></li>
        <li><a class="dropdown-item" href="#">Settings</a></li>
        <li><a class="dropdown-item" href="#">Profile</a></li>
        <li><hr class="dropdown-divider"></li>
        <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">Sign out</a></li>
      </ul>
    </div>
  </div>
</main>
<script src="{% static 'website/js/sidebars.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>